site_name: Mi Documentación
site_url: http://127.0.0.1

nav:
  - Home: index.md
  - Install: install.md
  - About: about.md
  - Diagramas:
      - Clases: diagramas/Ej_Mermaid Clases.md
      - Gantt: diagramas/Ej_Mermaid Gantt.md
      - MindMap: diagramas/Ej_Mermaid MindMap.md
      - Secuencia: diagramas/Ej_Mermaid Secuencia.md
  - Licencia: license.md

theme:
  name: "material"
  features:
    - navigation.footer
  palette:
    # Dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark Mode
      primary: indigo
      accent: deep purple
    
    # Light mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light Mode
      primary: blue
      accent: light blue
    
  

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - def_list
  - tables
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format 
  
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  social:
    - icon: simple/github
      link: https://github.com/JCTrapero
    - icon: simple/linkedin
      link: https://www.linkedin.com/in/juan-carlos-trapero-s%C3%A1nchez-08b17060/

copyright: Copyright &copy; 2024 Juan Carlos Trapero Sánchez